# Global authentication
allow_anonymous false
password_file /opt/homebrew/etc/mosquitto/passwd
acl_file /opt/homebrew/etc/mosquitto/acl.conf

# Message queue
queue_qos0_messages true
max_queued_messages 1000

# MQTT listener
listener 1883

# WebSocket listener
listener 9999
protocol websockets

connection school_tls
address pcfeib425t.vsb.cz:8883
remote_username server
remote_password Broker
topic /mschat/# both 1
cleansession false
notifications false
try_private true
restart_timeout 5 30
keepalive_interval 30

# SSL/TLS
bridge_cafile /opt/homebrew/etc/mosquitto/ca.crt
bridge_certfile /opt/homebrew/etc/mosquitto/server.crt
bridge_keyfile /opt/homebrew/etc/mosquitto/server.key
bridge_insecure true
